version: '3.8'

services:
  frontend:
    image: frontend:v1  # Replace with your built frontend image
    ports:
      - "3000:80"  # Maps host's port 3000 to container's port 3000
    networks:
      - app-network

  backend:
    image: claimready:v3   # Replace with your built backend image
    ports:
      - "8080:8000"  # Maps host's port 5000 to container's port 5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
